"""Public API for the dependency-free Anjo companion kernel."""

from .affect import (
    TurnShapePolicy,
    apply_length_factor,
    decoding_params,
    is_ambivalent,
    length_factor,
    mood_octant,
    turn_shape_directive,
)
from .appraisal import (
    AppraisalPolicyInput,
    AppraisalResult,
    InputAppraisal,
    appraise_input,
    appraise_turn,
    baseline_weight,
    decay_mood,
    decay_occ_carry,
    default_appraisal_policy,
    expectation_emotions,
    mood_inertia,
    stage_int,
    state_emotions,
)
from .engine import (
    BUILTIN_INTENTS,
    DEFAULT_ENGINE_LIMITS,
    CompanionEngine,
    EngineLimits,
    GateErrorMode,
    normalize_intent,
)
from .models import (
    AppraisalGoals,
    AttachmentState,
    CognitionState,
    CompanionState,
    DecodingParams,
    GateInput,
    GateResult,
    GenerateInput,
    MemoryCandidate,
    Message,
    PADMood,
    Personality,
    PresenceVector,
    RankedMemory,
    RelationshipState,
    RetrievalInput,
    TurnResult,
    UntrustedContext,
)
from .prompt import PromptInputs, PromptPolicy, build_system_prompt, build_untrusted_context
from .protocols import (
    AppraisalPolicy,
    ConversationTransaction,
    MemoryRetriever,
    ModelAdapter,
    StateStore,
)
from .retrieval import (
    candidate_score,
    mood_congruence_factor,
    rank_candidates,
    recency_weight,
    score_candidate,
    similarity_from_distance,
)
from .surfacing import build_presence_vector, clean_text, presence_line

__version__ = "0.1.0"

__all__ = [
    "BUILTIN_INTENTS",
    "DEFAULT_ENGINE_LIMITS",
    "AppraisalGoals",
    "AppraisalPolicy",
    "AppraisalPolicyInput",
    "AppraisalResult",
    "AttachmentState",
    "CognitionState",
    "CompanionEngine",
    "CompanionState",
    "ConversationTransaction",
    "DecodingParams",
    "EngineLimits",
    "GateErrorMode",
    "GateInput",
    "GateResult",
    "GenerateInput",
    "InputAppraisal",
    "MemoryCandidate",
    "MemoryRetriever",
    "Message",
    "ModelAdapter",
    "PADMood",
    "Personality",
    "PresenceVector",
    "PromptInputs",
    "PromptPolicy",
    "RankedMemory",
    "RelationshipState",
    "RetrievalInput",
    "StateStore",
    "TurnResult",
    "TurnShapePolicy",
    "UntrustedContext",
    "apply_length_factor",
    "appraise_input",
    "appraise_turn",
    "baseline_weight",
    "build_presence_vector",
    "build_system_prompt",
    "build_untrusted_context",
    "candidate_score",
    "clean_text",
    "decay_mood",
    "decay_occ_carry",
    "decoding_params",
    "default_appraisal_policy",
    "expectation_emotions",
    "is_ambivalent",
    "length_factor",
    "mood_congruence_factor",
    "mood_inertia",
    "mood_octant",
    "normalize_intent",
    "presence_line",
    "rank_candidates",
    "recency_weight",
    "score_candidate",
    "similarity_from_distance",
    "stage_int",
    "state_emotions",
    "turn_shape_directive",
]
